import type { BacktestResult } from "../types/result";
export const resultFixture: BacktestResult = {
  specification: {
    name: "sma-trend",
    symbol: "SPY",
    start: "2020-01-01",
    end: "2020-01-03",
    initial_capital: 10000,
    signal: "sma_trend",
    signal_parameters: { window: 3 },
    execution_timing: "next_open",
    position_sizing: "all_cash_no_fractional_shares",
    transaction_cost_bps: 5,
    benchmark: "buy_and_hold",
    metadata: {},
  },
  actual_start: "2020-01-01",
  actual_end: "2020-01-03",
  states: [
    {
      date: "2020-01-01",
      cash: 10000,
      shares: 0,
      asset_value: 0,
      equity: 10000,
      transaction_costs_paid: 0,
      exposure: 0,
      desired_position: "CASH",
    },
  ],
  trades: [],
  metrics: {
    total_return: 0.12,
    cagr: 0.1,
    annualized_volatility: 0.2,
    sharpe_ratio: 0.6,
    maximum_drawdown: -0.08,
    number_of_trades: 0,
    transaction_costs_paid: 0,
    percentage_time_invested: 0.5,
    risk_free_rate: 0,
    annualization_days: 252,
  },
  benchmark_metrics: {
    total_return: 0.1,
    cagr: 0.09,
    annualized_volatility: 0.18,
    sharpe_ratio: 0.5,
    maximum_drawdown: -0.1,
    number_of_trades: 1,
    transaction_costs_paid: 5,
    percentage_time_invested: 1,
    risk_free_rate: 0,
    annualization_days: 252,
  },
  benchmark_equity: [{ date: "2020-01-01", equity: 10000 }],
};
